Ext.define('Connect.model.User', {
	extend: 'Ext.data.Model',
	idProperty: 'esntl_id',
	fields: [	         
			 {name: 'esntl_id',			type: 'string'},
	         {name: 'emplyr_id',		type: 'string'},
	         {name: 'user_nm',			type: 'string'},
	         {name: 'password',			type: 'string'},
	         {name: 'password_hint',	type: 'string'},
	         {name: 'password_cnsr',	type: 'string'},
	         {name: 'empl_no',			type: 'string'},
	         {name: 'ihidnum',			type: 'string'},
	         {name: 'sexdstn_code',		type: 'string'},
	         {name: 'brthdy',			type: 'string'},
	         {name: 'area_no',			type: 'string'},
	         {name: 'house_middle_telno',	type: 'string'},
	         {name: 'house_end_telno',		type: 'string'},
	         {name: 'fxnum',			type: 'string'},
	         {name: 'house_adres',		type: 'string'},
	         {name: 'detail_adres',		type: 'string'},
	         {name: 'zip',				type: 'string'},
	         {name: 'offm_telno',		type: 'string'},
	         {name: 'mbtlnum',			type: 'string'},
	         {name: 'email_adres',		type: 'string'},
	         {name: 'ofcps_nm',			type: 'string'},
	         {name: 'group_id',			type: 'string'},
	         {name: 'orgnzt_id',		type: 'string'},
	         {name: 'pstinst_code',		type: 'string'},
	         {name: 'emplyr_sttus_code',type: 'string'},
	         {name: 'sbscrb_de',		type: 'date', dateFormat: 'Y-m-d H:i:s'},
	         {name: 'crtfc_dn_value',	type: 'string'},
	         {name: 'deptcd',			type: 'string'}
	]
}); 